version: "3.7"
services:

  db:
    image: mysql:5.7.34
    container_name: mysql-57
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 102030
    volumes: 
      - ./db/data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    depends_on: 
        - db
    ports:
      - 8080:8080